'use client';

import React, { useEffect } from 'react';
import { motion } from 'framer-motion';
import { 
  BarChart3, 
  MessageSquare, 
  Layers, 
  Image as ImageIcon,
  ArrowLeft,
  Smile,
  Meh,
  Frown,
  AlertTriangle
} from 'lucide-react';

import Image from 'next/image';
import { AnalysisResult, TopicItem } from '@/lib/types';

interface ResultsViewProps {
  data: AnalysisResult;
  onReset: () => void;
}

export default function ResultsView({ data, onReset }: ResultsViewProps) {
  useEffect(() => {
    console.log("🚀 Backend API Data:", data);
  }, [data]);

  const { summary, sentiment_distribution, topics, wordcloud_url, churn_risk_score } = data;

  // STRICT BYPASS: Converting to 'any' forces TypeScript to ignore the Uppercase/Lowercase type error entirely.
  const dist: any = sentiment_distribution || {};
  const safePositive = dist.positive || dist.Positive || 0;
  const safeNeutral = dist.neutral || dist.Neutral || 0;
  const safeNegative = dist.negative || dist.Negative || 0;

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="w-full max-w-6xl pb-32 px-4"
    >
      <div className="flex justify-between items-center mb-16 pt-4">
        <div>
          <h2 className="text-4xl md:text-6xl font-black tracking-tighter leading-tight">ANALYSIS RESULTS</h2>
          <p className="text-white/40 uppercase tracking-[0.3em] text-[10px] mt-2 font-black">AI Orchestration complete • Nodes active</p>
        </div>
        <button
          onClick={onReset}
          className="flex items-center gap-2 px-8 py-3 bg-white text-black rounded-full hover:bg-neutral-200 transition-all text-xs font-black tracking-widest uppercase shadow-[0_0_20px_rgba(255,255,255,0.2)]"
        >
          <ArrowLeft size={16} /> NEW ANALYSIS
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-6">
          <section className="bg-black/40 backdrop-blur-xl border border-white/10 rounded-3xl p-8 shadow-2xl">
            <div className="flex items-center gap-3 mb-6 text-white/60">
              <MessageSquare size={20} />
              <h3 className="font-bold uppercase tracking-widest text-sm">AI Executive Summary</h3>
            </div>
            <p className="text-xl leading-relaxed text-neutral-200 font-medium">
              &quot;{summary || "No summary generated by the engine."}&quot;
            </p>
          </section>

          <section className="bg-black/40 backdrop-blur-xl border border-white/10 rounded-3xl p-8 shadow-2xl">
            <div className="flex items-center gap-3 mb-8 text-white/60">
              <BarChart3 size={20} />
              <h3 className="font-bold uppercase tracking-widest text-sm">Sentiment Intelligence</h3>
            </div>
            
            <div className="flex items-end gap-2 h-48 mb-8">
              <div className="flex-1 flex flex-col items-center gap-4">
                <motion.div initial={{ height: 0 }} animate={{ height: `${safePositive}%` }} className="w-full bg-emerald-500/80 rounded-t-xl relative group">
                  <span className="absolute -top-8 left-1/2 -translate-x-1/2 font-bold text-emerald-400">{safePositive}%</span>
                </motion.div>
                <Smile className="text-emerald-500" />
              </div>
              <div className="flex-1 flex flex-col items-center gap-4">
                <motion.div initial={{ height: 0 }} animate={{ height: `${safeNeutral}%` }} className="w-full bg-blue-500/80 rounded-t-xl relative group">
                  <span className="absolute -top-8 left-1/2 -translate-x-1/2 font-bold text-blue-400">{safeNeutral}%</span>
                </motion.div>
                <Meh className="text-blue-500" />
              </div>
              <div className="flex-1 flex flex-col items-center gap-4">
                <motion.div initial={{ height: 0 }} animate={{ height: `${safeNegative}%` }} className="w-full bg-rose-500/80 rounded-t-xl relative group">
                  <span className="absolute -top-8 left-1/2 -translate-x-1/2 font-bold text-rose-400">{safeNegative}%</span>
                </motion.div>
                <Frown className="text-rose-500" />
              </div>
            </div>
          </section>
        </div>

        <div className="space-y-6">
          <section className="bg-black/40 backdrop-blur-xl border border-white/10 rounded-3xl p-8 shadow-2xl flex flex-col items-center text-center">
            <div className="flex items-center gap-2 mb-6 text-rose-500">
              <AlertTriangle size={20} />
              <h3 className="font-bold uppercase tracking-widest text-sm text-white/60">Churn Risk Score</h3>
            </div>
            <div className="text-6xl font-black text-rose-500 tracking-tighter mb-2">
              {churn_risk_score !== undefined ? `${churn_risk_score}%` : '0%'}
            </div>
            <p className="text-[10px] text-white/30 uppercase tracking-widest">Powered by XGBoost</p>
          </section>

          <section className="bg-black/40 backdrop-blur-xl border border-white/10 rounded-3xl p-8 shadow-2xl">
            <div className="flex items-center gap-3 mb-6 text-white/60">
              <Layers size={20} />
              <h3 className="font-bold uppercase tracking-widest text-sm">Discovered Topics</h3>
            </div>
            <div className="space-y-4">
              {topics?.length > 0 ? topics.map((t: TopicItem, i: number) => (
                <div key={i} className="group">
                  <div className="flex justify-between items-center mb-1">
                    <span className="text-sm font-medium text-white/80">{t.topic}</span>
                    <span className="text-xs font-mono text-white/40">{t.count}</span>
                  </div>
                  <div className="w-full h-1 bg-white/10 rounded-full overflow-hidden">
                    <motion.div initial={{ width: 0 }} animate={{ width: '100%' }} className="h-full bg-white/40" />
                  </div>
                </div>
              )) : (
                <p className="text-white/40 text-sm">No topics discovered.</p>
              )}
            </div>
          </section>

          {wordcloud_url && (
            <section className="bg-black/40 backdrop-blur-xl border border-white/10 rounded-3xl p-8 shadow-2xl">
              <div className="flex items-center gap-3 mb-6 text-white/60">
                <ImageIcon size={20} />
                <h3 className="font-bold uppercase tracking-widest text-sm">Visual Synthesis</h3>
              </div>
              <Image src={wordcloud_url} alt="Word Cloud" width={400} height={225} className="w-full h-full opacity-80" unoptimized />
            </section>
          )}
        </div>
      </div>
    </motion.div>
  );
}